language: python
python: 2.7
sudo: false
env:
  global:
    LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
  matrix:
    - TOXENV=check
    - TOXENV=2.6,coveralls,codecov
    - TOXENV=2.6-nocover
    - TOXENV=2.7,coveralls,codecov
    - TOXENV=2.7-nocover
    - TOXENV=3.3,coveralls,codecov
    - TOXENV=3.3-nocover
    - TOXENV=3.4,coveralls,codecov
    - TOXENV=3.4-nocover
    - TOXENV=pypy,coveralls,codecov
    - TOXENV=pypy-nocover
before_install:
  - python --version
  - virtualenv --version
  - pip --version
  - uname -a
  - lsb_release -a
  - |
    if [[ "${TOXENV}" =~ "pypy" ]]; then
        git clone https://github.com/yyuu/pyenv.git ~/.pyenv
        PYENV_ROOT="$HOME/.pyenv"
        PATH="$PYENV_ROOT/bin:$PATH"
        eval "$(pyenv init -)"
        pyenv install pypy-2.6.0
        pyenv global pypy-2.6.0
    fi
    pip install virtualenv
install:
  - pip install tox
script:
  - tox -v
after_failure:
  - cat .tox/*/log/*.log
notifications:
  email:
    on_success: never
    on_failure: always

